//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanaceyaUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket_Consist
    {
        public int ID_Consist { get; set; }
        public int ID_Basket { get; set; }
        public int ID_Medicines { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
    
        public virtual Baskets Baskets { get; set; }
        public virtual Medicines Medicines { get; set; }
    }
}
