//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanaceyaUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_Order { get; set; }
        public Nullable<int> ID_Status { get; set; }
        public int ID_Pay { get; set; }
        public int ID_Pharm { get; set; }
        public Nullable<int> ID_Basket { get; set; }
    
        public virtual Baskets Baskets { get; set; }
        public virtual Pay_Method Pay_Method { get; set; }
        public virtual Pharmacies Pharmacies { get; set; }
        public virtual Status Status { get; set; }
    }
}
